substitutions:
  ota_password: !secret template_ota_password
  api_encryption_key: !secret template_api_encryption_key
packages:
  - !include packages/common.yaml
esphome:
  name: template
  friendly_name: template
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
