substitutions:
  ota_password: !secret athom-rgbct-light-9240_ota_password
  api_encryption_key: !secret athom-rgbct-light-9240_api_encryption_key
packages:
  - !include packages/devices/athom-rgbct-light.yaml
esphome:
  name: athom-rgbct-light-9240
  friendly_name: "Athom RGBCT Light 9240"
