substitutions:
  ota_password: !secret athom-smart-plug-v2-33a7_ota_password
  api_encryption_key: !secret athom-smart-plug-v2-33a7_api_encryption_key
packages:
  - !include packages/devices/athom-smart-plug-v2.yaml
esphome:
  name: athom-smart-plug-v2-33a7
  friendly_name: "Athom Smart Plug V2 33a7"
