substitutions:
  ota_password: !secret sonoff-pow-ring-fc5a_ota_password
  api_encryption_key: !secret sonoff-pow-ring-fc5a_api_encryption_key
packages:
  - !include packages/devices/sonoff-pow-ring.yaml
esphome:
  name: sonoff-pow-ring-fc5a
  friendly_name: "Sonoff POW Ring fc5a"
