substitutions:
  ota_password: !secret xiao-esp32c3-media-player-b6f9_ota_password
  api_encryption_key: !secret xiao-esp32c3-media-player-b6f9_api_encryption_key

packages:
  - !include packages/devices/xiao-esp32c3-media-player.yaml

esphome:
  name: xiao-esp32c3-media-player-b6f9
  friendly_name: "XIAO ESP32C3 Media Player b6f9"
