sensor:
  - platform: cse7766
    voltage:
      name: "CSE7766: Voltage"
    current:
      name: "CSE7766: Current"
    power:
      name: "CSE7766: Power"
    energy:
      name: "CSE7766: Energy"
    apparent_power:
      name: "CSE7766: Apparent Power"
    reactive_power:
      name: "CSE7766: Reactive Power"
    power_factor:
      name: "CSE7766: Power Factor"
    uart_id: cse7766_uart
