external_components:
  - source:
      type: git
      url: https://github.com/fornellas/esphome
      ref: esphome-ld2450-zones
    refresh: 0s
    components: [ ld2450 ]

ld2450:
  id: ld2450_radar
  uart_id: uart_ld2450

binary_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    has_target:
      name: "LD2450: Has Target"
      disabled_by_default: true
    has_moving_target:
      name: "LD2450: Has Moving Target"
      disabled_by_default: true
    has_still_target:
      name: "LD2450: Has Still Target"
      disabled_by_default: true
    polygon_zones:
      - polygon_zone_id: ld2450_polygon_zone_1
        name: Polygon Zone 1 Presence
      - polygon_zone_id: ld2450_polygon_zone_2
        name: Polygon Zone 2 Presence
      - polygon_zone_id: ld2450_polygon_zone_3
        name: Polygon Zone 3 Presence

text:
  - platform: ld2450
    ld2450_id: ld2450_radar
    polygon_zones:
      - id: ld2450_polygon_zone_1
        name: Polygon Zone 1
      - id: ld2450_polygon_zone_2
        name: Polygon Zone 2
      - id: ld2450_polygon_zone_3
        name: Polygon Zone 3

sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    target_count:
      name: "LD2450: Target Count"
      disabled_by_default: true
    still_target_count:
      name: "LD2450: Still Target Count"
      disabled_by_default: true
    moving_target_count:
      name: "LD2450: Moving Target Count"
      disabled_by_default: true
    target_1:
      x:
        name: "LD2450: Target-1: X"
      y:
        name: "LD2450: Target-1: Y"
      speed:
        name: "LD2450: Target-1: Speed"
        disabled_by_default: true
      angle:
        name: "LD2450: Target-1: Angle"
        disabled_by_default: true
      distance:
        name: "LD2450: Target-1: Distance"
        disabled_by_default: true
      resolution:
        name: "LD2450: Target-1: Resolution"
        disabled_by_default: true
    target_2:
      x:
        name: "LD2450: Target-2: X"
      y:
        name: "LD2450: Target-2: Y"
      speed:
        name: "LD2450: Target-2: Speed"
        disabled_by_default: true
      angle:
        name: "LD2450: Target-2: Angle"
        disabled_by_default: true
      distance:
        name: "LD2450: Target-2: Distance"
        disabled_by_default: true
      resolution:
        name: "LD2450: Target-2: Resolution"
        disabled_by_default: true
    target_3:
      x:
        name: "LD2450: Target-3: X"
      y:
        name: "LD2450: Target-3: Y"
      speed:
        name: "LD2450: Target-3: Speed"
        disabled_by_default: true
      angle:
        name: "LD2450: Target-3: Angle"
        disabled_by_default: true
      distance:
        name: "LD2450: Target-3: Distance"
        disabled_by_default: true
      resolution:
        name: "LD2450: Target-3: Resolution"
        disabled_by_default: true
    zone_1:
      target_count:
        name: "LD2450: Zone-1: Target Count"
        disabled_by_default: true
      still_target_count:
        name: "LD2450: Zone-1: Still Target Count"
        disabled_by_default: true
      moving_target_count:
        name: "LD2450: Zone-1: Moving Target Count"
        disabled_by_default: true
    zone_2:
      target_count:
        name: "LD2450: Zone-2: Target Count"
        disabled_by_default: true
      still_target_count:
        name: "LD2450: Zone-2: Still Target Count"
        disabled_by_default: true
      moving_target_count:
        name: "LD2450: Zone-2: Moving Target Count"
        disabled_by_default: true
    zone_3:
      target_count:
        name: "LD2450: Zone-3: Target Count"
        disabled_by_default: true
      still_target_count:
        name: "LD2450: Zone-3: Still Target Count"
        disabled_by_default: true
      moving_target_count:
        name: "LD2450: Zone-3: Moving Target Count"
        disabled_by_default: true

switch:
  - platform: ld2450
    ld2450_id: ld2450_radar
    bluetooth:
      name: "LD2450: Bluetooth"
    multi_target:
      name: "LD2450: Multi Target"

number:
  - platform: ld2450
    ld2450_id: ld2450_radar
    presence_timeout:
      name: "LD2450: Presence Timeout"
    zone_1:
      x1:
        name: "LD2450: Zone-1: X1"
        disabled_by_default: true
      y1:
        name: "LD2450: Zone-1: Y1"
        disabled_by_default: true
      x2:
        name: "LD2450: Zone-1: X2"
        disabled_by_default: true
      y2:
        name: "LD2450: Zone-1: Y2"
        disabled_by_default: true
    zone_2:
      x1:
        name: "LD2450: Zone-2: X1"
        disabled_by_default: true
      y1:
        name: "LD2450: Zone-2: Y1"
        disabled_by_default: true
      x2:
        name: "LD2450: Zone-2: X2"
        disabled_by_default: true
      y2:
        name: "LD2450: Zone-2: Y2"
        disabled_by_default: true
    zone_3:
      x1:
        name: "LD2450: Zone-3: X1"
        disabled_by_default: true
      y1:
        name: "LD2450: Zone-3: Y1"
        disabled_by_default: true
      x2:
        id: ld2450_zone_3_x2
        disabled_by_default: true
      y2:
        name: "LD2450: Zone-3: Y2"
        disabled_by_default: true

button:
  - platform: ld2450
    ld2450_id: ld2450_radar
    factory_reset:
      name: "LD2450: Factory Reset"
    restart:
      name: "LD2450: Restart"

text_sensor:
  - platform: ld2450
    ld2450_id: ld2450_radar
    version:
      name: "LD2450: Version"
      disabled_by_default: true
    mac_address:
      name: "LD2450: MAC Address"
      disabled_by_default: true
    target_1:
      direction:
        name: "LD2450: Target-1: Direction"
        disabled_by_default: true
    target_2:
      direction:
        name: "LD2450: Target-2: Direction"
        disabled_by_default: true
    target_3:
      direction:
        name: "LD2450: Target-3: Direction"
        disabled_by_default: true

select:
  - platform: ld2450
    ld2450_id: ld2450_radar
    baud_rate:
      name: "LD2450: Baud rate"
      disabled_by_default: true
    zone_type:
      name: "LD2450: Zone type"
      disabled_by_default: true
