packages:
  - !include ../common.yaml
  - !include ../common-esp32.yaml

esphome:
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
    board_build.flash_mode: dio
  on_boot:
    priority: 600.0
    then:
      - if:
          condition:
            lambda: "return id(decoupled_mode);"
          then:
            - switch.turn_on: switch_relay

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf

globals:
  - id: decoupled_mode
    type: bool
    restore_value: yes
    initial_value: "false"

status_led:
  pin:
    # This is a second bright blue LED.
    number: GPIO9
    inverted: true
    ignore_strapping_warning: true
    id: status_led_blue

output:
  - platform: gpio
    # Whet this is high, dim red LED is lit.
    # When this is low, first bright blue LED is lit.
    pin: GPIO3
    inverted: true
    id: output_red_blue_led

  - platform: template
    id: output_template_light
    type: binary
    write_action:
      - if:
          condition:
            lambda: "return state;"
          then:
            - switch.turn_on: switch_relay
          else:
            - if:
                condition:
                  lambda: "return id(decoupled_mode);"
                then:
                  - light.turn_on: light1
                else:
                  - switch.turn_off: switch_relay

switch:
  - platform: gpio
    pin: GPIO5
    id: switch_relay
    internal: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - output.turn_on: output_red_blue_led
      - light.turn_on: light1
    on_turn_off:
      - output.turn_off: output_red_blue_led
      - light.turn_off: light1

  - platform: template
    name: "Decoupled Mode"
    icon: "mdi:link-variant-off"
    entity_category: config
    lambda: |-
      return id(decoupled_mode);
    turn_on_action:
      - globals.set:
          id: decoupled_mode
          value: "true"
      - switch.turn_on: switch_relay
    turn_off_action:
      - globals.set:
          id: decoupled_mode
          value: "false"

light:
  - platform: binary
    name: "Light"
    id: light1
    output: output_template_light

event:
  - platform: template
    name: "Button"
    id: event_button
    event_types:
      - "Pressed once"
      - "Pressed twice"
      - "Held down"

binary_sensor:
  - platform: gpio
    id: binary_sensor_button
    internal: true
    pin:
      inverted: true
      number: GPIO20
      mode:
        input: true
        pullup: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.25s
        then:
          - event.trigger:
              id: event_button
              event_type: "Pressed once"
          - if:
              condition:
                lambda: "return !id(decoupled_mode);"
              then:
                - switch.toggle: switch_relay
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.25s
          - ON for at most 0.5s
          - OFF for at least 0.25s
        then:
          - event.trigger:
              id: event_button
              event_type: "Pressed twice"
      - timing:
          - ON for at least 1s
        then:
          - event.trigger:
              id: event_button
              event_type: "Held down"
      - timing:
          - ON for at least 15s
        then:
          - button.press: button_factory_reset
