packages:
  - !include ../common.yaml
  - !include ../common-bk72xx.yaml

esphome:
  on_boot:
    - priority: 600.0
      then:
        - lambda: |-
            // Default: Connecting
            id(wifi_led_pwm).set_level(0.5);
            id(wifi_led_pwm).set_period(1000);
            id(wifi_led_pwm).turn_on();
  on_loop:
    then:
      - lambda: |-
          // Captive portal
          if(id(wifi_component).has_ap() && !id(wifi_component).has_sta()) {
            id(wifi_led_pwm).set_level(0.5);
            id(wifi_led_pwm).set_period(200);
          } else {
            id(wifi_led_pwm).set_period(1000);
            // Connected
            if(id(wifi_component).is_connected())
              id(wifi_led_pwm).set_level(1);
            // Connecting
            else
              id(wifi_led_pwm).set_level(0.5);
          }

bk72xx:
  board: wb2s

binary_sensor:
  - platform: gpio
    id: relay_button
    pin:
      number: P6
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: relay

output:
  - platform: slow_pwm
    id: wifi_led_pwm
    period: 1s
    pin:
      number: P7
      inverted: true

  - platform: gpio
    pin:
      number: P8
      inverted: true
    id: relay_led

switch:
  - platform: gpio
    name: "Power"
    id: relay
    icon: mdi:toggle-switch
    pin: P24
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: ""
    device_class: outlet
    on_turn_on:
      - output.turn_on: relay_led
    on_turn_off:
      - output.turn_off: relay_led
