substitutions:
  # This device is mounted upside down.
  ld2450_x_multiplier: "-1"

packages:
  - !include ../common.yaml
  - !include ../common-esp32.yaml
  - !include ../sensors/ld2450.yaml

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3

uart:
  id: uart_ld2450
  baud_rate: 256000
  tx_pin: 10
  rx_pin:
    number: 9
    ignore_strapping_warning: true
  parity: NONE
  stop_bits: 1
