esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: ESP32C3
  framework:
    type: esp-idf

binary_sensor:
  - platform: gpio
    pin:
      inverted: true
      number: GPIO20
      mode:
        input: true
        pullup: true
    name: "Button"
    on_press:
      then:
        - light.toggle: light1
    on_multi_click:
      - timing:
          - ON for at least 10s
        then:
          - button.press: button_factory_reset

output:
  - platform: gpio
    pin: GPIO5
    id: output_relay

  - platform: ledc
    pin: GPIO3
    inverted: true
    id: output_button_led

light:
  - platform: status_led
    pin:
      inverted: true
      number: GPIO9
      ignore_strapping_warning: true

  - platform: binary
    name: "Light"
    id: light1
    output: output_relay
    on_turn_on:
      - light.turn_on: light_button_led
    on_turn_off:
      - light.turn_off: light_button_led

  - platform: monochromatic
    id: light_button_led
    output: output_button_led
    default_transition_length: 0ms
