packages:
  - !include debug.yaml
  - !include logger.yaml
  - !include wifi.yaml

binary_sensor:
  - platform: status
    name: "Status"

button:
  - platform: factory_reset
    id: button_factory_reset
    name: "Factory Reset"

  - platform: restart
    name: "Restart"

  - platform: safe_mode
    name: "Safe Mode"

  - platform: shutdown
    name: "Shutdown"

sensor:
  - platform: uptime
    name: "Uptime"

text_sensor:
  - platform: uptime
    name: Uptime

  - platform: version
    name: "ESPHome Version"

factory_reset:
  resets_required: 5
  max_delay: 10s

safe_mode:

api:
  reboot_timeout: 0s
  encryption:
    key: ${api_encryption_key}

ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:
