sensor:
  - platform: debug
    min_free:
      name: "Debug: Heap Min Free"
    fragmentation:
      name: "Debug: Heap Fragmentation"
    # TODO This option requires component psram.
    # psram:
    #   name: "Debug: Free PSRAM"
